const ACTION = {
    // categories
    GET_CATEGORIES_REQUEST: 'GET_CATEGORIES_REQUEST',
    GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
    
    ADD_CATEGORY_REQUEST: 'ADD_CATEGORY_REQUEST',
    ADD_CATEGORY_SUCCESS: 'ADD_CATEGORY_SUCCESS',
    
    UPD_CATEGORY_REQUEST: 'UPD_CATEGORY_REQUEST',
    UPD_CATEGORY_SUCCESS: 'UPD_CATEGORY_SUCCESS',
    
    DEL_CATEGORY_REQUEST: 'DEL_CATEGORY_REQUEST',
    DEL_CATEGORY_SUCCESS: 'DEL_CATEGORY_SUCCESS',

    // subcategories    
    ADD_SUBCATEGORY_REQUEST: 'ADD_SUBCATEGORY_REQUEST',
    ADD_SUBCATEGORY_SUCCESS: 'ADD_SUBCATEGORY_SUCCESS',
    
    UPD_SUBCATEGORY_REQUEST: ' UPD_SUBCATEGORY_REQUEST',
    UPD_SUBCATEGORY_SUCCESS: 'UPD_SUBCATEGORY_SUCCESS',
    
    DEL_SUBCATEGORY_REQUEST: ' DEL_SUBCATEGORY_REQUEST',
    DEL_SUBCATEGORY_SUCCESS: 'DEL_SUBCATEGORY_SUCCESS',
    
    // error
    CATEGORIES_ERROR: 'CATEGORIES_ERROR',
}

export default ACTION;